---
abstract: 'use Git commands with Future'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Cwd: '0'
  Exporter: '0'
  File::Basename: '0'
  File::Path: '2.07'
  File::Spec: '0'
  File::Spec::Functions: '0'
  Test::More: '0.88'
  lib: '0'
  overload: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 1
generated_by: 'Dist::Zilla, CPAN::Meta::Converter'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Git-Background
no_index:
  directory:
    - corpus
    - t
    - xt
requires:
  Carp: '0'
  File::Temp: '0'
  Future: '0.05'
  Proc::Background: '1.30'
  Scalar::Util: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Git-Background/issues
  homepage: https://github.com/skirmess/Git-Background
  repository: https://github.com/skirmess/Git-Background.git
version: '0.001'
x_spdx_expression: BSD-2-Clause-FreeBSD
